"""add phone number to user table

Revision ID: 5e1ec15cc1a7
Revises: 72d7ff72bb98
Create Date: 2026-02-01 09:44:44.339371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1ec15cc1a7'
down_revision: Union[str, Sequence[str], None] = '72d7ff72bb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('todos', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_priority'), 'todos', ['priority'], unique=False)
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_index(op.f('ix_todos_priority'), table_name='todos')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.alter_column('todos', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    # ### end Alembic commands ###
